language: node_js
node_js:
- '6'
branches:
  only:
  - master
cache:
  directories:
  - frontend/node_modules
  - node_modules
services:
- mongodb
install:
- npm install
- cd frontend
- npm install
- cd ..
script:
- npm run build
- mv frontend/dist ./
- rm -rf frontend
- mv dist frontend
notifications:
  slack: laecherbar:y1NWyusbhnKv2tGC3XQCmmJW
env:
  global:
    secure: xJaSTNBRaMQyy8VumXPJSsu8ZMy6Y8FT9ldvdYpCx5BTH8wMyhNs5D5XUcOuAFBjv50jMZhHyl+QmF/miM3MD5e1MMSVR4wzJPyVXMqM6FJBAoHGrT2FgXHa83jYG5r7dR6Hh8A76OMOavSYoVt6z+IrNTVwmOwXr7ZnL3r/GsMBP/b2lUg9hzSe2Yh2Z+ZFkYjH9N9ej/tyg/mJ/ZFrvTIPczpxXvkWOvT4aJUCZ7PxrSXyTJ7NC0PoKJ/XiRTaLJp+A3VUy9L4yJ7OQOhz4gKNwsXyS35VFyE6F/+l1TvCVRmS4qBo56ofaWzbnP+go57Z8PV0bmdoOVsPwxTLoCLj1erMhFWKbPPZrFZMOOharSoLRz0iQ+3bEtXWNavSYxhP0WpBVNybGaqZDkBKomxXM6QtfiTPynYErpgTmCkXqJPC8GKAy7IBhcXEo+JQtJf0Gz2zwnhi+38OSwjumL9o1GUVvQkwTmdpPuauL6Z7YkhRvoArTEFjFNG5+wDuovMXedfB9UA4VOHnOKVDonX30xd+BGB9cbUA4O3g65Xr3f3UQpvvRFuBeLnn+zHfz1+Tjc4DyQVf1dkTDX1jBoHlgbcCEkAjCmPk1subHhVyYOFdcimhziZuLhg+Kaf5DZ4xX1IuZvJoDZn2uDlTXdenLOuklTveH7lCxNL9pDM=
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAICBN3DTQNYATHTAA
  secret_access_key:
    secure: sbW59TF9HJYMrxOFaHFQphZwp9eC/46zKnkNpqQg+YUBCkjozteeKukWFON1/jxySpGtyBAx7ZKLH3lHjcrb7e4vNUA5BxC0guQ5pTCrzn+7gp4/B+8TCJjFgPJk6NSPELdNr3SdJuNF9CUfypaZzrd1v4m7BdY752JnbM2tr1SNJWb+aUYSecPo52oXZEdDqMIAizwtyTM28ItqcYCap22sskCUOwHiTqfMNVxS65ovowKMFwZeCipiwysgRVVG7qE96rQ7NCK/leKDd1k8J4sXiKcACTlq3biUqs79mIee7TO4hMbSKfu2sncFrpHDs7PLovJ9pMQK7t4h4YlG78fnA24PQblBD8wHAg90SNtXfeeWSDqEG0A5/Z4iENwAe9k+BL7y7+ks5uOXnsKRBn8HEWaT982ooC9gE4h/gkYjgxlbt75VV4OzHVrR1Hq3OLstO0Tp0x57M972P1jpJ3drinupEQa0ZbRxfoWq+O9y3G8NHDMk1dtFhQr5Jhz26bnMfuDe1heey2+jEnHr1RAsesGBRPrk8Pf0IwCUdiDsyBJSAfoXn2BLxovZM3k+OAKiggajTggwjmHGRjHwNTl0hCbLcC09CkoDBu8W+nmOZqAJwQo1rOfNt2qi9Bubj77T9Bl0fSrMMY7Sy/TqkhNx035UoQZHdF2uDTY/pxw=
  region: eu-central-1
  app: Translator
  env: Translator-env
  bucket_name: elasticbeanstalk-eu-central-1-264024695840
  on:
    repo: enjoping/translationFun
